apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
  labels:
    app: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-cronjob
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command: {{ .Values.cronjob.command | toJson }}
              args: {{ .Values.cronjob.args | toJson }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
